# zsh/zprofile

mkdir -p "$HOME/.cache/zsh"
emulate sh -c '. ~/.profile'

if type startx >/dev/null && (( UID )) && (( XDG_VTNR == 1 )) && [[ -z $DISPLAY && $TTY = /dev/tty1 ]]; then
  exec startx
fi

# vim: syn=sh
