# ~/.config/zsh/zshrc

zmodload zsh/complist
autoload -Uz compinit && compinit
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

setopt auto_cd correct
setopt extended_glob append_history extended_history share_history
setopt hist_find_no_dups hist_expire_dups_first hist_ignore_dups
setopt hist_ignore_space hist_reduce_blanks hist_save_no_dups hist_verify
setopt prompt_subst
unsetopt flow_control

HISTSIZE=20000
SAVEHIST=10000
HISTFILE="$HOME/.logs/zhistory"

## configs
for cfg in aliases bindings fun git hook style util; do
	[[ -r "$HOME/.config/zsh/$cfg.zsh" ]] && \
		source "$HOME/.config/zsh/$cfg.zsh"
done
unset cfg

## prompt
PROMPT='%(?..%B%F{red}exit %?%f%b
)%B%F{black}[%b%f'\
'${vcs_info_msg_0_}'\
'%F{11}%~%B%F{black}]%b%f'\
'%(!.%F{red}#%f.%F{blue}$%f) '
SPROMPT="Correct %B%F{red}%R%b%f to %B%F{green}%r%b%f [nyae]? "
