" ~/.vim/vimrc

set nocompatible
call pathogen#infect()
filetype plugin indent on
syntax on
let g:zenburn_old_Visual = 1
let g:zenburn_alternate_Visual = 1
let g:zenburn_high_Contrast = 1
colorscheme zenburn

" searching
set hlsearch
set ignorecase
set incsearch
set smartcase
set wrapscan

" formatting
set cinoptions=(0
set expandtab
set formatoptions+=qn1
set nowrap
set shiftwidth=4
set softtabstop=2
set tabstop=4

" editing
set clipboard=unnamed
set list listchars=tab:»\ ,extends:$,precedes:^,trail:·
set nrformats+=alpha

" vim ui
set autoread
set autowrite
set completeopt=longest,menuone,preview
set hidden
set history=50
set laststatus=2
set mouse=a
set scrolloff=3
set shortmess=atToOI
set showcmd
set statusline=%f\ \ %<%y%m%r%=%12.(\(%l,%c%V\)%)\ \ %P
set title
set ttimeoutlen=50
set whichwrap+=<,>,[,],h,l
set wildmenu wildmode=list:longest,full

set wildignore+=*.aux,*.out,*.toc
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpg
set wildignore+=*.a,*.o,*.obj,*.so,*.hi
set wildignore+=.git,.hg

noremap Y y$
nnoremap ZW :write<cr>
nnoremap <silent> <space> :nohlsearch<bar>:echo<cr>
nnoremap <f5> :!make<cr>
command! -bar W silent! exec "write !sudo tee % >/dev/null" | silent! edit!

nnoremap <leader>b :buffers<cr>:buffer<space>
nnoremap <leader>d :diffupdate<cr>
nnoremap <leader>q :quitall<cr>

" pane movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" fugitive
nnoremap <leader>gg :copen<cr>:Ggrep<space>
nnoremap <silent> <leader>gs :Gstatus<cr>
nnoremap <silent> <leader>gd :Gdiff<cr>
nnoremap <silent> <leader>ge :Gedit<cr>
nnoremap <silent> <leader>gb :Gblame<cr>

" autocommands
au BufReadPost *
 \ if line("'\"") > 0 && line("'\"") <= line("$") |
 \ exe "normal g`\"" | endif
