" ~/.vim/vimrc

set nocompatible
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
syntax on
let g:zenburn_high_Contrast = 1
colorscheme zenburn

" searching
set hlsearch
set ignorecase
set incsearch
set smartcase
set wrapscan

" formatting
set cinoptions=(0
set expandtab
set formatoptions+=qn1
set nolist
set nowrap
set shiftwidth=4
set softtabstop=2
set tabstop=4

" editing
set clipboard=unnamed
set list listchars=tab:»\ ,extends:$,precedes:^,trail:·
set nrformats+=alpha

" vim ui
set autoread
set autowrite
set completeopt=longest,menuone,preview
set cursorline
set equalalways
set hidden
set history=50
set laststatus=2
set mouse=a
set ruler
set scrolloff=3
set shortmess=atToOI
set showcmd
set title
set whichwrap+=<,>,[,],h,l
set wildmenu wildmode=list:longest,full

set wildignore+=*.aux,*.out,*.toc
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpg
set wildignore+=*.a,*.o,*.obj,*.so,*.hi
set wildignore+=.git,.hg

" backup
set dir=~/.cache/vim/tmp
set backup backupdir=~/.cache/vim/backup
set undofile undodir=~/.cache/vim/undo
set viminfo+=n~/.cache/vim/viminfo

noremap Y y$
nnoremap ZW :write<cr>
nnoremap <leader>q :quitall<cr>
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<cr>
nnoremap <F5> :!make<cr>
cmap w!! w !sudo tee % >/dev/null<cr>:e!<cr><cr>

" pane movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" fugitive
nnoremap <leader>gg :copen<cr>:Ggrep 
nnoremap <silent> <leader>gs :Gstatus<cr>
nnoremap <silent> <leader>gd :Gdiff<cr>
nnoremap <silent> <leader>ge :Gedit<cr>
nnoremap <silent> <leader>gb :Gblame<cr>

" autocommands
au BufReadPost *
 \ if line("'\"") > 0 && line("'\"") <= line("$") |
 \ exe "normal g`\"" | endif
