# alacritty/alacritty.toml

[font]
normal = { family = "Fantasque Sans Mono" }
size = 12

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#121212"
foreground = "#bbbdbb"
bright_foreground = "#ffffff"

[colors.hints]
start = { foreground = "#1c1c1c", background = "#88ff00" }
end = { foreground = "#1c1c1c", background = "#ffc524"}

[colors.normal]
black =   "#282a2e"
red =     "#af3a3a"
green =   "#96a034"
yellow =  "#e2935b"
blue =    "#5581a7"
magenta = "#855d99"
cyan =    "#56958d"
white =   "#bbbdbb"

[colors.bright]
black =   "#373b41"
red =     "#e06666"
green =   "#c2cc66"
yellow =  "#facb70"
blue =    "#84aed3"
magenta = "#c69bdd"
cyan =    "#91cfc6"
white =   "#d5d9d6"

[selection]
save_to_clipboard = true

[cursor.style]
blinking = "Never"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(?:[[:alpha:]][+-.[:alnum:]]*:)//(?:[-[:alnum:]]+(\\.[-[:alnum:]]+)*)?(?:/[-[:alnum:]_.!~*'();/?:@&=+$,#%]*)?"
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
action = "Copy"
hyperlinks = true
regex = "(?:[[:alpha:]][+-.[:alnum:]]*:)//(?:[-[:alnum:]]+(\\.[-[:alnum:]]+)*)?(?:/[-[:alnum:]_.!~*'();/?:@&=+$,#%]*)?"
binding = { key = "U", mods = "Control|Shift" }

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },

{ key = "Tab",       mods = "Control", chars = "\u001b[27;5;9~"  },
{ key = "Return",    mods = "Control", chars = "\u001b[27;5;13~" },
{ key = "'",         mods = "Control", chars = "\u001b[27;5;39~" },
{ key = "Comma",     mods = "Control", chars = "\u001b[27;5;44~" },
{ key = "Period",    mods = "Control", chars = "\u001b[27;5;46~" },
{ key = "Key1",      mods = "Control", chars = "\u001b[27;5;49~" },
{ key = "Key9",      mods = "Control", chars = "\u001b[27;5;57~" },
{ key = "Semicolon", mods = "Control", chars = "\u001b[27;5;59~" },

{ key = 10,      mods = "Control|Shift", chars = "\u001b[27;6;40~" }, # C-(
{ key = 11,      mods = "Control|Shift", chars = "\u001b[27;6;41~" }, # C-)
{ key = 13,      mods = "Control|Shift", chars = "\u001b[27;6;43~" }, # C-+
{ key = 6,       mods = "Control|Shift", chars = "\u001b[27;6;37~" }, # C-%
{ key = "Colon", mods = "Control|Shift", chars = "\u001b[27;6;58~" },
{ key = 51,      mods = "Control|Shift", chars = "\u001b[27;6;60~" }, # C-<
{ key = 52,      mods = "Control|Shift", chars = "\u001b[27;6;62~" }, # C->
{ key = 53,      mods = "Control|Shift", chars = "\u001b[27;6;63~" }, # C-?

{ key = "Tab",    mods = "Control|Alt",  chars = "\u001b[27;13;9~" },
{ key = "Return", mods = "Control|Alt",  chars = "\u001b[27;13;13~" },
{ key = "'",      mods = "Control|Alt",  chars = "\u001b[27;13;39~" },
{ key = "Comma",  mods = "Control|Alt",  chars = "\u001b[27;13;44~" },
{ key = "Period", mods = "Control|Alt",  chars = "\u001b[27;13;46~" },
{ key = 6,  mods = "Control|Shift|Alt",  chars = "\u001b[27;14;37~" }, # C-M-%
]
